version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my_root_password
      - MYSQL_DATABASE = ${DB_NAME}
      - MYSQL_USER = ${DB_USER}
      - MYSQL_PASSWORD = ${DB_PASSWORD}

  app:
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME = ${DB_NAME}
      - DB_USER = ${DB_USER}
      - DB_PASSWORD = ${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD = ${MYSQL_ROOT_PASSWORD}
      - DEBUG=1
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./welcomeHome:/welcomeHome
      - dev-static-data:/vol/web
    depends_on:
      - db
    command: >
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000'

volumes:
  dev-static-data: