version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    restart: always
    volumes:
      - dev-static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DEBUG=1
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE= ${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
     - db_data:/var/lib/mysql
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - dev-static-data:/vol/static
volumes:
  dev-static-data:
  db_data: