# Generated by Django 4.2.2 on 2023-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("countryDescription", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=255)),
                (
                    "specialConditionsForUkrainianWomen",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "medicalInsuranceForNonCitizens",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "medicalInsuranceCoverageForPregnancyAndChildbirth",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "organizationOfPrenatalCare",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "prenatalCareForNonCitizens",
                    models.CharField(blank=True, max_length=255),
                ),
                ("costOfDelivery", models.CharField(blank=True, max_length=255)),
                (
                    "organizationOfDelivery",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "naturalBirthOrCesareanSection",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "citizenshipOfChildByBirth",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "prospectsOfParentsObtainingCitizenship",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "durationOfMaternityLeave",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "preparationCoursesForChildbirth",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "durationOfJobProtectionForMother",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "paymentsDuringPregnancy",
                    models.CharField(blank=True, max_length=255),
                ),
                ("childBenefits", models.CharField(blank=True, max_length=255)),
                (
                    "benefitsForMothersAndChildren",
                    models.CharField(blank=True, max_length=255),
                ),
                ("breastfeedingSupport", models.CharField(blank=True, max_length=255)),
                (
                    "postnatalSupportGroups",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "arrangementOfChildCareFacilities",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "mandatoryAgeForKindergarten",
                    models.CharField(blank=True, max_length=255),
                ),
                ("costOfDaycare", models.CharField(blank=True, max_length=255)),
                ("nursery", models.CharField(blank=True, max_length=255)),
                ("costOfNursery", models.CharField(blank=True, max_length=255)),
                ("mandatorySchoolAge", models.CharField(blank=True, max_length=255)),
                (
                    "bonusesForHaving23Children",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "conditionsForSingleMothers",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "conditionsForChildrenWithDisabilities",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "referencesToAssociationsFundsForMoms",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "doctorAppointmentBookingAndPhysicianReviews",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "immigrationConditionsResidencePermit",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "referencesToMigrantCommunities",
                    models.CharField(blank=True, max_length=255),
                ),
                ("psychologicalSupport", models.CharField(blank=True, max_length=255)),
                (
                    "additionalUsefulResourcesAndLinks",
                    models.CharField(blank=True, max_length=255),
                ),
            ],
        ),
    ]
