# Generated by Django 4.2.2 on 2023-07-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="countryDescription",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
