# Generated by Django 4.2.2 on 2023-07-29 04:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_additionalusefulresourcesandlinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='additionalUsefulResourcesAndLinks_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='additionalUsefulResourcesAndLinks_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='bonusesForHaving23Children_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='bonusesForHaving23Children_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='conditionsForChildrenWithDisabilities_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='conditionsForChildrenWithDisabilities_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='conditionsForSingleMothers_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='conditionsForSingleMothers_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='costOfDaycare_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='costOfDaycare_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='costOfNursery_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='costOfNursery_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='doctorAppointmentBookingAndPhysicianReviews_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='doctorAppointmentBookingAndPhysicianReviews_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='immigrationConditionsResidencePermit_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='immigrationConditionsResidencePermit_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='mandatorySchoolAge_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='mandatorySchoolAge_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='nursery_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='nursery_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='psychologicalSupport_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='psychologicalSupport_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='referencesToAssociationsFundsForMoms_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='referencesToAssociationsFundsForMoms_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='referencesToMigrantCommunities_ru',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='referencesToMigrantCommunities_uk',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
