# Generated by Django 4.2.2 on 2023-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_country_additionalusefulresourcesandlinks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="language",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
