# Generated by Django 4.2.2 on 2023-07-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_country_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="additionalUsefulResourcesAndLinks",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="arrangementOfChildCareFacilities",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="benefitsForMothersAndChildren",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="bonusesForHaving23Children",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="breastfeedingSupport",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="childBenefits",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="citizenshipOfChildByBirth",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="conditionsForChildrenWithDisabilities",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="conditionsForSingleMothers",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="costOfDaycare",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="costOfDelivery",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="costOfNursery",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="countryDescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="doctorAppointmentBookingAndPhysicianReviews",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="durationOfJobProtectionForMother",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="durationOfMaternityLeave",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="immigrationConditionsResidencePermit",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="mandatoryAgeForKindergarten",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="mandatorySchoolAge",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="medicalInsuranceCoverageForPregnancyAndChildbirth",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="medicalInsuranceForNonCitizens",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="naturalBirthOrCesareanSection",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="nursery",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="organizationOfDelivery",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="organizationOfPrenatalCare",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="paymentsDuringPregnancy",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="postnatalSupportGroups",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="prenatalCareForNonCitizens",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="preparationCoursesForChildbirth",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="prospectsOfParentsObtainingCitizenship",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="psychologicalSupport",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="referencesToAssociationsFundsForMoms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="referencesToMigrantCommunities",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="specialConditionsForUkrainianWomen",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
