# Generated by Django 4.2.2 on 2023-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_country_additionalusefulresourcesandlinks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
