# Generated by Django 4.2.2 on 2023-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_countryfilters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfilters',
            name='citizenshipByBirth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='countryfilters',
            name='freeKindergarten',
            field=models.BooleanField(default=False),
        ),
    ]
