# Generated by Django 4.2.2 on 2023-07-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_country_code_alter_country_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="language",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
